add: custom quote block
instill-ai/instill.tech pull request #420
Opened 2022-12-16 17:31 UTC by CaCaBlocker

2022-12-18 10:20 UTC, EiffelFly commented
HI @CaCaBlocker Thanks for your first PR in instill-ai's official website, we really appreciate your contribution, it means a lot to us. I would like to bring up a suggestion about the content of the PR first.

Could you please add the structure into the PR content like below

```
Because: (You could write the reason and reference the issue here)

This commit: (Elaborate how you implement this PR)
```

You could find a example here (please don't use #close command in your PR content)

2022-12-19 07:30 UTC, CaCaBlocker commented
Hi, @EiffelFly.
I just updated the PR content according to your request.
**Please check it and I hope your feedback.**

2022-12-22 00:10 UTC, EiffelFly requested changes
I think your code style is good! Please adjust these minor changes first. After that we can talk about the visual style

2022-12-22 09:39 UTC, CaCaBlocker commented
@EiffelFly I updated the code. Please check it.

2022-12-22 10:33 UTC, EiffelFly commented on src/components/ui/MdxQuoteBlock.tsx
> +        <p className="m-0 p-1">{content}</p>
I think the `m-1` is redundant here, please remove it.

2022-12-22 12:00 UTC, CaCaBlocker commented on src/components/ui/MdxQuoteBlock.tsx
> +        <p className="m-0 p-1">{content}</p>
Sorry about that. I just finished.

2022-12-30 06:34 UTC, EiffelFly commented
@CaCaBlocker 

I had altered the style to fit our design guide better. Besides that, I had altered the structure of the component too

- I think we should not provide position prop for user to change the position of quote block. In the end the width of this component will be as same as its container (Sorry for not bringing this info upfront)
- I move the block class because it is not necessary too
- Generally, we don't recommend the nested padding in near element so I recommend removing the padding of child and move it to its parent. (This way we could make debug style easier)
- I had adjusted the dark mode variant.
- I had changed the color to adapt instill-ai color set.

Here is the component that I come up with.

```ts
export const MdxQuoteBlock = ({ content, source }: MdxQuoteBlockProps) => {
  return (
    <div className="border-l-4 border-instillGrey90 px-4 py-1 dark:border-instillGrey50">
      <div className="font-sans text-lg">{content}</div>
      <div className="text-right font-sans text-lg">
        <span>&mdash; From </span>
        <span className="font-sans text-lg underline underline-offset-2">
          {source}
        </span>
      </div>
    </div>
  );
};
```

I think after this issue we could merge this PR!!

2023-01-05 10:30 UTC, CaCaBlocker commented
@EiffelFly 
I updated the code according to your recommendations. What you suggested are all right for me, and I didn't pay attention to such problems(for example, dark mode). I learned a lot from you.

2023-01-06 00:42 UTC, EiffelFly commented on src/pages/_app.tsx
> +      position={props.position}
@CaCaBlocker This position props should be removed!

2023-01-06 00:44 UTC, EiffelFly commented
> I updated the code according to your recommendations. What you suggested are all right for me, and I didn't pay attention to such problems(for example, dark mode). I learned a lot from you.

No problem! We are really appreciate your contribution and this PR is going to be our first merged PR into frontend codebase. @CaCaBlocker Good job!

2023-01-06 01:35 UTC, CaCaBlocker commented on src/pages/_app.tsx
> +      position={props.position}
@EiffelFly  Sorry about that. I consider why I missed that and I'd like to hear your opinion about this update.

src/pages/_app.tsx

>   MdxYoutubeEmbed,
>   MdxQuoteBlock,
>   **MdxQuoteBlockProps,**
> } from "@/components/ui";

> QuoteBlock: (props: **MdxQuoteBlockProps**) => (
> ),

2023-01-06 02:29 UTC, EiffelFly commented
@CaCaBlocker You may need to rebase our main again. During the development of this PR we had rolled out lots of things. Please rebase it and make sure lint is passing

2023-01-06 04:13 UTC, closed without merging