New VDP 101 tutorials
instill-ai/instill.tech pull request #451
Opened 2023-01-17 21:58 UTC by bryan107

Because

- VDP 101 was created to provider new users a step-by-step tutorials. The aim is to ensure inexperience users including students can easily get start with these tutorials.  

This commit

- 6 new tutorials documents 
- some big fix to ensure readability. 
- still need to check how to organise it with the original tutorials and make sure all the links works (there are cross-reference links between new tutorials yet have public links).

2023-01-24 01:14 UTC, xiaofei-du requested changes
Wait for the following issues to be resolved
- https://github.com/instill-ai/instill.tech/issues/452 
- https://github.com/instill-ai/instill.tech/issues/455

2023-01-24 01:14 UTC, xiaofei-du commented on tutorials/vdp-101-1-introduction.mdx
> +useCase: "Prototyping"
Can use a new use case type for all the VDP 101 tutorials.

2023-01-25 10:52 UTC, bryan107 commented
Waiting for the following issues to be resolved

- #461 

This PR will also be released with the example PR https://github.com/instill-ai/vdp/pull/187

2023-01-25 10:54 UTC, bryan107 commented on tutorials/vdp-101-1-introduction.mdx
> +useCase: "Prototyping"
Both issues were resolved after rebase.

2023-03-06 04:23 UTC, merged