Add Feedback link on the Righthandsidebar
instill-ai/instill.tech pull request #640
Opened 2023-10-24 04:25 UTC by Smartmind12

Because

- It adds "Give feedback" link on every documentation page that will redirect user to create new issue about documentation

This commit

- closes the first part of the issue https://github.com/instill-ai/community/issues/394

2023-10-25 14:03 UTC, iamnamananand996 requested changes
Hi @Smartmind12, thanks for your contribution, I have added some suggested changes please have a look.

2023-10-25 14:03 UTC, iamnamananand996 commented on src/pages/docs/[...path].tsx
> +              }
`githubEditUrl` missing as it is required according to component.

2023-10-25 14:03 UTC, iamnamananand996 commented on src/components/ui/ContributeLinks.tsx
> +        className="group flex flex-row gap-x-2.5"
give some space or margin between both the `a` tag. maybe `mt-2`

2023-10-25 17:38 UTC, Smartmind12 commented on src/pages/docs/[...path].tsx
> +              }
It is already a part of the code in Line 263!

2023-10-25 17:47 UTC, Smartmind12 commented on src/components/ui/ContributeLinks.tsx
> +        className="group flex flex-row gap-x-2.5"
Done the needful!

2023-10-25 17:48 UTC, Smartmind12 commented
@iamnamananand996 I made the changes so kindly have a look!

2023-10-26 17:38 UTC, iamnamananand996 requested changes
Hi @Smartmind12 , appreciate your effort, I have added some comment please have a look,
after that it should be good to merge.

2023-10-26 17:38 UTC, iamnamananand996 commented on src/pages/docs/[...path].tsx
> +              }
```
<aside className="hidden pb-10 xl:col-span-2 xl:block">
        {headers ? (
            <RightSidebar
              githubEditUrl={
                "https://github.com/instill-ai/instill.tech/edit/main" +
                router.asPath +
                `.${router.locale}` +
                ".mdx"
              }
             headers={headers}
           />
       ) : null}
 </aside>
<aside className="hidden pb-10 xl:col-span-2 xl:block">
          {headers ? (
            <RightSidebar
              feedbackUrl={
                "https://github.com/instill-ai/community/issues/new/choose"
              }
              headers={headers}
            />
          ) : null}
 </aside>
```

I think this should be written like below

```
<aside className="hidden pb-10 xl:col-span-2 xl:block">
       {headers ? (
          <RightSidebar
              githubEditUrl={
                "https://github.com/instill-ai/instill.tech/edit/main" +
                router.asPath +
                `.${router.locale}` +
                ".mdx"
              }
              feedbackUrl={
                "https://github.com/instill-ai/community/issues/new/choose"
              }
              headers={headers}
            />
       ) : null}
</aside>
```
as I see ` RightSidebarProps` expect 3 params

https://github.com/instill-ai/instill.tech/blob/b2d99be90f1db137d97ff6fea6a10bb9ee723169/src/components/docs/RightSidebar.tsx#L8

2023-10-26 17:38 UTC, iamnamananand996 commented on src/components/ui/ContributeLinks.tsx
> +        className="group flex flex-row gap-x-2.5 mt-2"
`group flex flex-row gap-x-2.5 mt-2`

we will not need `mt-2` here please remove it

2023-10-26 17:38 UTC, iamnamananand996 commented on src/components/ui/ContributeLinks.tsx
> +        className="group flex flex-row gap-x-2.5 mt-4"
`group flex flex-row gap-x-2.5 mt-4`
 
please make it 

`group flex flex-row gap-x-2.5 mt-2`

2023-10-29 04:10 UTC, Smartmind12 commented on src/pages/docs/[...path].tsx
> +              }
I understand and have made the changes.

2023-10-29 04:11 UTC, Smartmind12 commented on src/components/ui/ContributeLinks.tsx
> +        className="group flex flex-row gap-x-2.5 mt-2"
Yes done

2023-10-29 04:11 UTC, Smartmind12 commented on src/components/ui/ContributeLinks.tsx
> +        className="group flex flex-row gap-x-2.5 mt-4"
Done

2023-10-29 06:33 UTC, iamnamananand996 commented
Hi @Smartmind12,

LGTM, we can merge this, before that we can take pull from latest `main` to avoid any conflicts.

Please help to merge this PR 
cc - @EiffelFly

2023-10-29 10:54 UTC, EiffelFly approved these changes
@Smartmind12 Thank for your contribution!!

2023-10-29 10:55 UTC, merged