docs(blog): Update hacktoberfest 2023 closing blog post
instill-ai/instill.tech pull request #657
Opened 2023-11-06 14:37 UTC by ShihChun-H

Because

- Hacktoberfest has come to the end

This commit

- update the Hacktoberfest 2023 closing blog post
- update the contributors' name

2023-11-06 16:40 UTC, xiaofei-du approved these changes

2023-11-06 17:01 UTC, xiaofei-du requested changes
Please see the above comments.

2023-11-06 17:01 UTC, xiaofei-du commented on blog/hacktoberfest-2023-closing.mdx
> +    - Workout Procedure Generator
Same as above. If these wonderful contributors have their GitHub accounts, we can add them.

2023-11-06 17:01 UTC, xiaofei-du commented on blog/hacktoberfest-2023-closing.mdx
> +- **Syed Zubeen**
Same as above

2023-11-06 17:01 UTC, xiaofei-du commented on blog/hacktoberfest-2023-closing.mdx
> +    - **Sajda Kabir**
Same as above

2023-11-06 17:04 UTC, xiaofei-du commented
Please remove this half-down article. Curious why you did not directly edit this article, but instead made a new one.

![image](https://github.com/instill-ai/instill.tech/assets/66248476/430dec24-ccd5-4bcc-8be9-b3eed0da8859)

2023-11-06 17:05 UTC, xiaofei-du commented on blog/hacktoberfest-2023-closing.mdx
> +- **Sajda Kabir** - https://github.com/instill-ai/instill.tech/pull/625
Please provide a brief summary of each PR contribution to the readers.

2023-11-06 17:06 UTC, xiaofei-du requested changes
@ShihChun-H, I have added extra comments, please check.

2023-11-06 17:06 UTC, xiaofei-du commented on blog/hacktoberfest-2023-closing.mdx
> +- **Rutam Mishra** - https://dev.to/rutamhere/building-an-instill-ai-pipeline-in-5-minutes-4fp2
Please provide a brief summary of this tutorial to the readers.

2023-11-07 03:15 UTC, ShihChun-H commented on blog/hacktoberfest-2023-closing.mdx
> +- **Sajda Kabir** - https://github.com/instill-ai/instill.tech/pull/625
Hi @xiaofei-du, I did not create a new one. I changed the name of the file/title, maybe that is why it is identified as a new one. From this branch, I only see one closing blog post, basically, it is the same one.

2023-11-07 03:15 UTC, ShihChun-H commented on blog/hacktoberfest-2023-closing.mdx
> +publishedOn: "2023-10-23T18:00:00"
Hi @xiaofei-du, can you further explicit which part needs to be updated? Thanks. Other than `PublishedOn`, it looks good to me.

2023-11-07 03:16 UTC, ShihChun-H commented
> Please remove this half-down article. Curious why you did not directly edit this article, but instead made a new one.
> 
> ![image](https://user-images.githubusercontent.com/66248476/280789791-430dec24-ccd5-4bcc-8be9-b3eed0da8859.png)

Hi @xiaofei-du , I did not create a new one. I changed the name of the file/title, maybe that is why it is identified as a new one. From this branch, I only see one closing blog post, basically, it is the same one.

2023-11-10 15:03 UTC, xiaofei-du commented on blog/hacktoberfest-2023-closing.mdx
> +publishedOn: "2023-10-23T18:00:00"
yeah, the publish date

2023-11-10 15:04 UTC, xiaofei-du approved these changes

2023-11-11 14:40 UTC, merged