docs(tutorial): publish webpage interaction tutorial
instill-ai/instill.tech pull request #844
Opened 2024-05-15 15:05 UTC by ShihChun-H

Because

- webpage pipeline tutorial draft completed

This commit

- webpage pipeline tutorial publication

2024-05-16 08:34 UTC, GeorgeWilliamStrong reviewed
**Minor formatting comment**
When I select the `formatted` output option for the [5 Seconds Previews pipeline](https://instill.tech/instill-wombat/pipelines/jumbotron-webpage-5-sec-previews) the output blocks alternate between having a grey shaded and white background. Is this intentional? To me it implies that the outputs follow some alternating structure when they are just a list. (See attached image).

![CleanShot 2024-05-16 at 09 29 10@2x](https://github.com/instill-ai/instill.tech/assets/42313440/3eb278b1-553d-4a5e-b88e-282bfae3feb3)

2024-05-16 08:42 UTC, GeorgeWilliamStrong commented on tutorials/webpage-interaction.mdx
**Minor grammatical change**

Please change
Line 118: To extract content scraped from the webpage by Website Component

To
Line 118: To extract content scraped from the webpage by the Website Component

2024-05-16 20:34 UTC, pinglin requested changes
Please change according to the review comments.

2024-05-16 20:34 UTC, pinglin commented on tutorials/webpage-interaction.mdx
> +        - To extract content scraped from the webpage by Website Component, add **'Webpage Text Content'** field with Title **`Webpage Content`**, Key **`webpage_content`** and Value **`${web_scraper
```suggestion
        - To extract content scraped from the webpage by the Website component, add **'Webpage Text Content'** field with Title **`Webpage Content`**, Key **`webpage_content`** and Value **`${web_scraper.output.pages[0].link_text}`**.
```

2024-05-17 15:23 UTC, GeorgeWilliamStrong approved these changes

2024-05-17 15:26 UTC, merged