docs(tutorial): add new tutorial for serving custom models in Instill Core
instill-ai/instill.tech pull request #877
Opened 2024-06-04 13:23 UTC by GeorgeWilliamStrong

Because

- We need a new tutorial on creating custom models on Instill Model 

This commit

- Creates the new tutorial

2024-06-04 13:28 UTC, orangecoloured approved these changes
Code-wise LGTM.

2024-06-04 17:12 UTC, heiruwu submitted a review, later dismissed
The tutorial looks awesome!

2024-06-04 23:57 UTC, pinglin requested changes
The content is fantastic and well-written. 

Besides some minor layout and fixing links requests further, can we also add a section `Step 6. Tear Everything Down` to guide the users how to undeploy a model and tear down the Instill Core instance by running:
```
inst local undeploy
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +   guide](./docs/core/deployment) for recommended resource settings.
```suggestion
   guide](/docs/core/deployment) for recommended resource settings.
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +refer to the [deployment guide](./docs/core/deployment) which covers alternative
```suggestion
refer to the [deployment guide](/docs/core/deployment) which covers alternative
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +Configure Model Settings" />
```suggestion
<ZoomableImg src="/tutorial-assets/model-serving-on-instill-core/T1.png" alt="Configure Model Settings" />
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +repo: {user_id}/{model_id}
```suggestion
repo: USER_ID/MODEL_ID
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +Importantly, you must replace `{user_id}` with `admin`, and replace `{model_id}`
```suggestion
Importantly, you must replace `USER_ID` with `admin`, and replace `MODEL_ID`
```

, to align with the [doc](https://www.instill.tech/docs/model/prepare#model-configuration).

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +model falls under the `text_generation_chat` AI task, and so we will make use of
```suggestion
model falls under the [Text Generation Chat](https://www.instill.tech/docs/model/ai-task#text-generation-chat) AI task, and so we will make use of
```
, to cite the AI task reference.

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +define the input format for the text generation chat AI task, and the
```suggestion
define the input format for the [Text Generation Chat](https://www.instill.tech/docs/model/ai-task#text-generation-chat) AI task, and the
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +        )
```suggestion
        task_text_generation_chat_output: TextGenerationChatInput = (
            StandardTaskIO.parse_task_text_generation_chat_output(sequences=sequences)
        )
```

I supposed the type hint should work as in the input case?

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +        )
```suggestion
        task_text_generation_chat_output: TextGenerationChatInput = (
            StandardTaskIO.parse_task_text_generation_chat_output(sequences=sequences)
        )
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +able to login to Docker. To do this, you first need to create an API token by:
```suggestion
able to login to the hosted Docker registry. To do this, you first need to create an API token by:
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +Create API Token" />
```suggestion
<ZoomableImg src="/tutorial-assets/model-serving-on-instill-core/T2.png" alt="Create API Token" />
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +Now we can login to Docker on the **🔮 Instill Core** instance by running:
```suggestion
Now we can login to the Docker register in the **🔮 Instill Core** instance by running:
```

2024-06-04 23:57 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +   $ export INSTILL_API_TOKEN=********
```suggestion
   export INSTILL_API_TOKEN=********
```

, to align with the other command line code snippets.

2024-06-05 08:51 UTC, GeorgeWilliamStrong commented on tutorials/model-serving-on-instill-core.mdx
> +        )
I don't think so, I think for the output case this returns `serialized_bytes_tensor`.

2024-06-05 08:51 UTC, GeorgeWilliamStrong commented on tutorials/model-serving-on-instill-core.mdx
> +        )
I don't think so, I think for the output case this returns `serialized_bytes_tensor`.

2024-06-05 09:03 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
> +        )
Hey @heiruwu, can you help confirm this? There is a type `TextGenerationChatOutput` in the [protogen-python](https://github.com/instill-ai/protogen-python/blob/main/model/model/v1alpha/task_text_generation_chat_pb2.pyi#L89), and I feel the input and output expression here could be symmetric.

2024-06-05 13:19 UTC, heiruwu commented on tutorials/model-serving-on-instill-core.mdx
> +        )
no, the `task_text_generation_chat_output` here is the serialized bye string that will be passed back to model-backend, not the user.
the `TextGenerationChatOutput` class is the response for the trigger endpoint.

2024-06-05 13:21 UTC, heiruwu commented on tutorials/model-serving-on-instill-core.mdx
> +        )
the `TextGenerationChatInput` class is written [here](https://github.com/instill-ai/python-sdk/blob/main/instill/helpers/const.py#L58-L68) for the user's convenience to understand the request data structure after its been deserialized, not by the protogen-go

2024-06-05 13:54 UTC, GeorgeWilliamStrong commented on tutorials/model-serving-on-instill-core.mdx
> +        )
@pinglin @heiruwu are we ok to resolve and merge?

2024-06-06 07:52 UTC, merged