docs(model): improve consistency and fix typos
instill-ai/instill.tech pull request #895
Opened 2024-06-13 09:36 UTC by GeorgeWilliamStrong

Because

- Spotted some inconsistencies that needed to be fixed

This commit

- Improves consistency and fixes typos

2024-06-18 23:43 UTC, pinglin requested changes
@GeorgeWilliamStrong I've left some questions and minor revision requests. Please check. 🙏

2024-06-18 23:43 UTC, pinglin commented on docs/model/create/namespace.en.mdx
> +  src="/docs-assets/model/create-model-namespace.mp4"
Documentation website supports only GIF file at the moment. Nonetheless I think we can remove the animation for now and add it back once the `ERROR` model state is changed to `NO VERSION`.

2024-06-18 23:43 UTC, pinglin commented on docs/model/state.en.mdx
> +  src="/docs-assets/model/machine-state-diagram-v4.mp4"
Documentation website supports only GIF file at the moment.

2024-06-18 23:43 UTC, pinglin commented on docs/model/state.en.mdx
> +information regarding replicas.
```suggestion
traffic.
```
I suggest we make this page self-contained so the reader doesn't need to refer an external document (given also that the cited URL pointing to another unspecific documentation page).

2024-06-18 23:43 UTC, pinglin commented on docs/model/state.en.mdx
> +separate processes. The number of replicas is autoscaled according to the model
I am not quite sure why a model version deployment consists of a number of replicas? Isn't it starting from 0 replica and scaling to only 1? Only if the traffic accumulated, it will continuously scale up.

What does "These are essentially clones of the model class that are launched in
separate processes" mean? Particularly, do we have the "model class" definition somewhere in the documentation?

2024-06-18 23:43 UTC, pinglin commented on docs/vdp/introduction.en.mdx
> +flow, i.e. the **input** field of each component:
```suggestion
flow, i.e., the **input** field of each component:
```
[Reference](https://www.grammarbook.com/blog/commas/commas-part-10/)

2024-06-18 23:43 UTC, pinglin commented on docs/vdp/introduction.zh-CN.mdx
> +flow, i.e. the **input** field of each component:
```suggestion
flow, i.e., the **input** field of each component:
```
[Reference](https://www.grammarbook.com/blog/commas/commas-part-10/)

2024-06-18 23:43 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
>  To get started, navigate to the Model page in the Console window and click the
```suggestion
To get started, navigate to the Model page in the console window and click the
```

2024-06-18 23:43 UTC, pinglin commented on tutorials/model-serving-on-instill-core.mdx
>  1. Selecting the profile icon in the top right corner of the Console window and
```suggestion
1. Selecting the profile icon in the top right corner of the console window and
```

2024-06-18 23:43 UTC, pinglin commented on docs/model/state.en.mdx
> +page in the Console and view the `Status` field.
```suggestion
page in the console and view the `Status` field.
```

2024-06-18 23:43 UTC, pinglin commented on docs/model/state.zh-CN.mdx
> +page in the Console and view the `Status` field.
```suggestion
page in the console and view the `Status` field.
```

2024-06-19 08:37 UTC, GeorgeWilliamStrong commented on docs/model/state.en.mdx
> +  src="/docs-assets/model/machine-state-diagram-v4.mp4"
fixed in latest commit

2024-06-19 08:38 UTC, GeorgeWilliamStrong commented on docs/model/create/namespace.en.mdx
> +  src="/docs-assets/model/create-model-namespace.mp4"
fixed in latest commit

2024-06-19 21:44 UTC, merged