docs(tutorial): update aigc x web3 tutorial
instill-ai/instill.tech pull request #931
Opened 2024-07-10 23:22 UTC by GeorgeWilliamStrong

Because

- The AIGC x Web3 tutorial was out of date with respect to the latest changes to VDP, Instill Core/Cloud and the UI.

This commit

- Updates the AIGC x Web3 tutorial

2024-07-12 09:42 UTC, xiaofei-du requested changes
1. I have updated the phrase "trigger a pipeline" to "run a pipeline" in the tutorial because soon we will have event-triggered pipelines, making "trigger" a term with a specific meaning. Feel free to make further updates based on my suggestions.

2. We are using different styles for the screenshot tool, including variations in:

  - Arrow color & size
  - Number (1, 2, 3) color & size

We should unify these styles in our future tutorials. Let's ask our design team to help us pin down a palette.

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +`ai-art-to-web3` pipeline by `instill-ai`, then clone the pipeline by following
```suggestion
`ai-art-to-web3` pipeline by `instill-ai`, then clone the [pipeline](https://instill.tech/instill-ai/pipelines/ai-art-to-web3) by following
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +`blockchain-1`. Under the `Capture token` field, fill in your Capture
@GeorgeWilliamStrong, for future reference, we should use meaningful component names. For example, instead of `blockchain-1`, we can name it `asset-creator`, and instead of `ai-1`, we can name it `ai-art-generator`.

Since generating the screenshot for the tutorial will take more time, it's fine not to update this tutorial.

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
>  ## Trigger the pipeline to generate and register AI-generated content into Web3 asset with low-code method
```suggestion
## Run the pipeline to generate and register AI-generated content into Web3 asset with low-code method
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +3. Click the `Run` button to trigger the pipeline.
```suggestion
3. Click the `Run` button to run the pipeline.
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
>    alt="Trigger the pipeline by clicking Run"
```suggestion
  alt="Run the pipeline"
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +your data. Here's a step-by-step guide on how to trigger the pipeline and create
```suggestion
your data. Here's a step-by-step guide on how to run the pipeline and create
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +you the necessary details to trigger the pipeline.
```suggestion
you the necessary details to run the pipeline.
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +token to trigger the pipeline.
```suggestion
token to run the pipeline.
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
>  ### Trigger the pipeline
```suggestion
### Run the pipeline
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +To trigger the pipeline, you can use cURL with the provided API token as a
```suggestion
To run the pipeline, you can use cURL with the provided API token as a
```

2024-07-12 09:42 UTC, xiaofei-du commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
>  ```shellscript Trigger-via-Instill-Core
```suggestion
```shellscript Run-via-Instill-Core
```

2024-07-15 23:28 UTC, GeorgeWilliamStrong commented on tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
> +`blockchain-1`. Under the `Capture token` field, fill in your Capture
Yes, completely agree!

2024-07-16 08:11 UTC, merged